linters:
  enable:
    - errcheck
    - staticcheck
    - unused
    - gosimple
    - govet
    - ineffassign
    - typecheck

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - staticcheck
      text: "SA1019:" # Ignore deprecation warnings in tests
