/*
Copyright 2024.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
)

// DiagnosisTarget defines the target resource for diagnosis
type DiagnosisTarget struct {
	// Namespace of the target resource
	Namespace string `json:"namespace,omitempty"`
	// Name of the target resource (e.g. Pod name)
	Name string `json:"name,omitempty"`
	// Kind of the target resource (e.g. Pod, Deployment)
	Kind string `json:"kind,omitempty"`
}

// DiagnosisPolicy defines the constraints for the diagnosis process
type DiagnosisPolicy struct {
	// MaxSteps is the maximum number of agent steps allowed
	// +kubebuilder:default=10
	MaxSteps int `json:"maxSteps,omitempty"`
}

// DiagnosisTaskSpec defines the desired state of DiagnosisTask
type DiagnosisTaskSpec struct {
	// Target identifies the resource to diagnose
	Target DiagnosisTarget `json:"target"`
	// Policy controls the diagnosis execution
	Policy DiagnosisPolicy `json:"policy,omitempty"`
	// AlertContext provides context about the alert that triggered this diagnosis
	AlertContext *AlertContext `json:"alertContext,omitempty"`
	// Approved indicates whether the diagnosis actions are approved by a human
	Approved bool `json:"approved,omitempty"`
}

// AlertContext contains metadata about the alert
type AlertContext struct {
	// Name of the alert (e.g., KubePodCrashLooping)
	Name string `json:"name,omitempty"`
	// Labels associated with the alert (e.g., severity=critical, reason=OOMKilled)
	Labels map[string]string `json:"labels,omitempty"`
}

// DiagnosisPhase describes the current state of the diagnosis
// +kubebuilder:validation:Enum=Pending;Running;WaitingApproval;Completed;Failed
type DiagnosisPhase string

const (
	PhasePending         DiagnosisPhase = "Pending"
	PhaseRunning         DiagnosisPhase = "Running"
	PhaseWaitingApproval DiagnosisPhase = "WaitingApproval"
	PhaseCompleted       DiagnosisPhase = "Completed"
	PhaseFailed          DiagnosisPhase = "Failed"
)

// Finding represents a key discovery made during the diagnosis process
type Finding struct {
	// Step index in the diagnosis process
	Step int `json:"step"`
	// Name of the tool executed
	ToolName string `json:"toolName,omitempty"`
	// Arguments passed to the tool
	ToolArgs string `json:"toolArgs,omitempty"`
	// Summary of the tool output generated by LLM
	Summary string `json:"summary,omitempty"`
	// Timestamp of the finding
	Timestamp string `json:"timestamp,omitempty"`
}

// DiagnosisReport contains the findings of the diagnosis
type DiagnosisReport struct {
	// RootCause identified by the agent
	RootCause string `json:"rootCause,omitempty"`
	// Suggestion for remediation
	Suggestion string `json:"suggestion,omitempty"`
}

// DiagnosisTaskStatus defines the observed state of DiagnosisTask
type DiagnosisTaskStatus struct {
	// Phase represents the current stage of diagnosis
	Phase DiagnosisPhase `json:"phase,omitempty"`
	// Report contains the final diagnosis results
	Report *DiagnosisReport `json:"report,omitempty"`
	// History logs the agent's actions (for debugging/audit)
	History []string `json:"history,omitempty"`
	// Checkpoint stores the intermediate findings for crash recovery
	Checkpoint []Finding `json:"checkpoint,omitempty"`
	// MatchedSkill indicates the name of the skill matched for this task
	MatchedSkill string `json:"matchedSkill,omitempty"`
	// Message provides additional information about the current status (e.g. why approval is needed)
	Message string `json:"message,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status

// DiagnosisTask is the Schema for the diagnosistasks API
type DiagnosisTask struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`

	Spec   DiagnosisTaskSpec   `json:"spec,omitempty"`
	Status DiagnosisTaskStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// DiagnosisTaskList contains a list of DiagnosisTask
type DiagnosisTaskList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []DiagnosisTask `json:"items"`
}

func init() {
	SchemeBuilder.Register(&DiagnosisTask{}, &DiagnosisTaskList{})
}
