//go:build !ignore_autogenerated

/*
Copyright 2024.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AlertContext) DeepCopyInto(out *AlertContext) {
	*out = *in
	if in.Labels != nil {
		in, out := &in.Labels, &out.Labels
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AlertContext.
func (in *AlertContext) DeepCopy() *AlertContext {
	if in == nil {
		return nil
	}
	out := new(AlertContext)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DiagnosisPolicy) DeepCopyInto(out *DiagnosisPolicy) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DiagnosisPolicy.
func (in *DiagnosisPolicy) DeepCopy() *DiagnosisPolicy {
	if in == nil {
		return nil
	}
	out := new(DiagnosisPolicy)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DiagnosisReport) DeepCopyInto(out *DiagnosisReport) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DiagnosisReport.
func (in *DiagnosisReport) DeepCopy() *DiagnosisReport {
	if in == nil {
		return nil
	}
	out := new(DiagnosisReport)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DiagnosisTarget) DeepCopyInto(out *DiagnosisTarget) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DiagnosisTarget.
func (in *DiagnosisTarget) DeepCopy() *DiagnosisTarget {
	if in == nil {
		return nil
	}
	out := new(DiagnosisTarget)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DiagnosisTask) DeepCopyInto(out *DiagnosisTask) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DiagnosisTask.
func (in *DiagnosisTask) DeepCopy() *DiagnosisTask {
	if in == nil {
		return nil
	}
	out := new(DiagnosisTask)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *DiagnosisTask) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DiagnosisTaskList) DeepCopyInto(out *DiagnosisTaskList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]DiagnosisTask, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DiagnosisTaskList.
func (in *DiagnosisTaskList) DeepCopy() *DiagnosisTaskList {
	if in == nil {
		return nil
	}
	out := new(DiagnosisTaskList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *DiagnosisTaskList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DiagnosisTaskSpec) DeepCopyInto(out *DiagnosisTaskSpec) {
	*out = *in
	out.Target = in.Target
	out.Policy = in.Policy
	if in.AlertContext != nil {
		in, out := &in.AlertContext, &out.AlertContext
		*out = new(AlertContext)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DiagnosisTaskSpec.
func (in *DiagnosisTaskSpec) DeepCopy() *DiagnosisTaskSpec {
	if in == nil {
		return nil
	}
	out := new(DiagnosisTaskSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DiagnosisTaskStatus) DeepCopyInto(out *DiagnosisTaskStatus) {
	*out = *in
	if in.Report != nil {
		in, out := &in.Report, &out.Report
		*out = new(DiagnosisReport)
		**out = **in
	}
	if in.History != nil {
		in, out := &in.History, &out.History
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Checkpoint != nil {
		in, out := &in.Checkpoint, &out.Checkpoint
		*out = make([]Finding, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DiagnosisTaskStatus.
func (in *DiagnosisTaskStatus) DeepCopy() *DiagnosisTaskStatus {
	if in == nil {
		return nil
	}
	out := new(DiagnosisTaskStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Finding) DeepCopyInto(out *Finding) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Finding.
func (in *Finding) DeepCopy() *Finding {
	if in == nil {
		return nil
	}
	out := new(Finding)
	in.DeepCopyInto(out)
	return out
}
